name: quick_assist_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  just_audio: ^0.9.36
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/first_aid/bleeding/
    - assets/first_aid/fracture/
    - assets/first_aid/chocking/
    - assets/first_aid/fainting/
    - assets/first_aid/burn/